### ISSUE TITLE
Server memory runs full with latest updates

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_connector#6] opened 2022-05-10 15:37 UTC
With the latest versions, our memory on the server is currently full.
Files are stored, presumably per executed cronjob, according to the pattern tx_campuseventsconnector_"000sjJ" under webroot/var/transient/tx_campuseventsconnector_000sjJ.

**Comment by bahammes** [comment] 2022-05-11 10:27
We cannot replicate this problem. The file import functions have not been changed in the last updates.
The file references are created with the core method \TYPO3\CMS\Core\Resource\ResourceStorage::addFile
This function also deletes/moves the temporary files from var/transient/... the folder configured in the scheduler task.
This works without problems in our test environments and production systems.

Can you please specify, which version of TYPO3 and campus_events_connector (3.0.2 or 2.0.3) you are using?

**Comment by dennismetz** [comment] 2022-05-11 10:45
Hi, yes, of course, that's what we noticed on two systems:

System1:
PHP 7.4.6
TYPO3 10.4.27
campus_events_connector 3.0.2
campus_events_convert2news 3.0.2
campus_events_frontend 3.0.2

System2:
PHP 7.4.6
TYPO3 11.5.9
campus_events_connector 3.0.2
campus_events_convert2news 3.0.2
campus_events_frontend 3.0.2

When I try to open the created cron in the planner:
Return value of BrainAppeal\CampusEventsConnector\Task\EventImportTask::getApiVersion() must be of the type string, null returned

Looks like the cron has changed between versions and would need to be resaved?

**Comment by bahammes** [comment] 2022-05-16 10:22
Thank you for your feedback.

While we still cannot reproduce the problem with the deletion of temporary files, we have refactored the file import, especially to improve the check for existing files.
Additionally we have added a fallback for deleting the temporary files created by the importer. Normally this should not be necessary, because the temporary files should be moved by the ResourceFactory. The fallback function deletes the temporary files, if the core function does not move a temporary file for any reason.

The problem in the scheduler task has also been fixed. It seems, that you have not set an API-Version yet.
Please select the correct API-Version depending on your Campus Events installation.

You can find the update in the latest version 3.0.3:
https://github.com/BrainAppeal/campus_events_connector/releases/tag/3.0.3

**Comment by brain-appeal** [comment] 2022-06-10 09:10
Closing ticket since problem seems to be resolved with current version.

**Comment by JoergOswald** [comment] 2022-11-05 09:28
Closing ticket since problem seems to be resolved with current version.

**Closed as completed** 2023-04-13 06:12 UTC
Labels: question
